# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "7cb0cd42e524631ff29e0e811d3f3b48"
name = "empowered-gadget-app"
application_url = "https://empowered-gadget-app.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = [ "https://empowered-gadget-app.gadget.app/api/connections/auth/shopify/callback" ]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://empowered-gadget-app.gadget.app/api/webhooks/shopify"

[app_proxy]
url = "https://empowered-gadget-app.gadget.app/api/graphql"
subpath = "empowered-gadget-app-api"
prefix = "apps"
