import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyOrder" model, go to https://empowered-gadget-app.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Order",
  fields: {},
  shopify: {
    fields: {
      billingAddress: { filterIndex: false },
      browserIp: { filterIndex: false, searchIndex: false },
      buyerAcceptsMarketing: {
        filterIndex: false,
        searchIndex: false,
      },
      cancelReason: { filterIndex: false, searchIndex: false },
      cancelledAt: { searchIndex: false },
      cartToken: { filterIndex: false, searchIndex: false },
      checkoutToken: { searchIndex: false },
      clientDetails: { filterIndex: false },
      closedAt: { filterIndex: false, searchIndex: false },
      confirmationNumber: { filterIndex: false, searchIndex: false },
      confirmed: { filterIndex: false, searchIndex: false },
      currency: { filterIndex: false, searchIndex: false },
      currentShippingPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentSubtotalPrice: {
        filterIndex: false,
        searchIndex: false,
      },
      currentSubtotalPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalAdditionalFeesSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalDiscounts: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalDiscountsSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalDutiesSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalPrice: { filterIndex: false, searchIndex: false },
      currentTotalPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalTax: { filterIndex: false, searchIndex: false },
      currentTotalTaxSet: { filterIndex: false, searchIndex: false },
      customerLocale: { filterIndex: false, searchIndex: false },
      discountApplications: {
        filterIndex: false,
        searchIndex: false,
      },
      discountCodes: { filterIndex: false },
      dutiesIncluded: { filterIndex: false, searchIndex: false },
      email: true,
      estimatedTaxes: { filterIndex: false, searchIndex: false },
      financialStatus: { searchIndex: false },
      fulfillmentStatus: { searchIndex: false },
      landingSite: { filterIndex: false },
      lineItems: true,
      merchantOfRecordAppId: {
        filterIndex: false,
        searchIndex: false,
      },
      name: true,
      note: true,
      noteAttributes: { filterIndex: false, searchIndex: false },
      orderStatusUrl: { filterIndex: false, searchIndex: false },
      originalTotalAdditionalFeesSet: {
        filterIndex: false,
        searchIndex: false,
      },
      originalTotalDutiesSet: {
        filterIndex: false,
        searchIndex: false,
      },
      paymentGatewayNames: { filterIndex: false },
      phone: { filterIndex: false },
      poNumber: { filterIndex: false },
      presentmentCurrency: { filterIndex: false, searchIndex: false },
      processedAt: { searchIndex: false },
      referringSite: { filterIndex: false },
      shippingAddress: { filterIndex: false },
      shop: { searchIndex: false },
      shopifyCreatedAt: { filterIndex: false, searchIndex: false },
      shopifyUpdatedAt: { filterIndex: false, searchIndex: false },
      sourceIdentifier: { filterIndex: false },
      sourceName: { filterIndex: false, searchIndex: false },
      sourceUrl: { filterIndex: false },
      subtotalPrice: { filterIndex: false, searchIndex: false },
      subtotalPriceSet: { filterIndex: false, searchIndex: false },
      tags: true,
      taxExempt: { filterIndex: false, searchIndex: false },
      taxLines: { filterIndex: false, searchIndex: false },
      taxesIncluded: { filterIndex: false, searchIndex: false },
      test: { filterIndex: false, searchIndex: false },
      token: { filterIndex: false, searchIndex: false },
      totalDiscounts: { filterIndex: false, searchIndex: false },
      totalDiscountsSet: { filterIndex: false, searchIndex: false },
      totalLineItemsPrice: { filterIndex: false, searchIndex: false },
      totalLineItemsPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      totalOutstanding: { filterIndex: false, searchIndex: false },
      totalPrice: { filterIndex: false, searchIndex: false },
      totalPriceSet: { filterIndex: false, searchIndex: false },
      totalShippingPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      totalTax: { filterIndex: false, searchIndex: false },
      totalTaxSet: { filterIndex: false, searchIndex: false },
      totalTipReceived: { filterIndex: false, searchIndex: false },
      totalWeight: { filterIndex: false, searchIndex: false },
    },
  },
};
